---
- name: restart vm 
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: restart node
      shell: sleep 2 && shutdown -r now
      async: 300
      poll: 0
      become: true

    - name: waiting for node booting up
      local_action: wait_for
      args:
        host: " {{ inventory_hostname }} "
        port: 22
        delay: 10
        timeout: 180
      become: false
