---
- name: restart vm 
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: restart node
      shell: sleep 2 && shutdown -r now
      async: 300
      poll: 0
      become: true

    - name: waiting for node booting up
      local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
      become: false
